// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EFCore;

#nullable disable

namespace Service_Project.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241010190019_mig2")]
    partial class mig2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.CarrierConfigurations", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("carrierCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("carrierID")
                        .HasColumnType("int");

                    b.Property<int>("carrierMaxDesi")
                        .HasColumnType("int");

                    b.Property<int>("carrierMinDesi")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("CarrierConfigurations");
                });

            modelBuilder.Entity("Entities.Models.Carriers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("carrierIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("carrierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("carrierPlusDesiCost")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("Entities.Models.Orders", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("carrierID")
                        .HasColumnType("int");

                    b.Property<decimal>("orderCarrierCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("orderDesi")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
